name: Build Launcher EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build EXE with Maven
      run: mvn clean package
      
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: ZRLauncher-App
        path: target/ZRLauncher.exe
